[package]
name = "wasi-clocks"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen = { workspace = true }

[features]
default = [ "symmetric" ]
symmetric = [ "wit-bindgen/symmetric" ]
canonical = [ "wit-bindgen/canonical" ]
