[package]
name = "implementation"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen = { workspace = true }

[features]
default = [ "canonical" ]
symmetric = [ "wit-bindgen/symmetric" ]
canonical = [ "wit-bindgen/canonical" ]

[lib]
crate-type = ["cdylib"]
