package test:complex;

// interface external {
//     resource subscriber;
// }

interface sender {
    use test:shm/pub-sub.{subscriber};
    start: func() -> subscriber;
}

interface receiver {
    use test:shm/pub-sub.{subscriber};
    start: func(source: subscriber, block: bool);
}

world send-world {
    export sender;
}

world rec-world {
    export receiver;
}

world starter {
    import sender;
    import receiver;
}
